sudo: false
language: ruby
rvm:
  - 2.4.1
env:
  - START_SIMPLECOV=1
addons:
  code_climate:
    repo_token:
      secure: "Tsz+lAiRyzIoEIAS3wjixe8INQroVixx95kZMLwH9SWXfVIzPmIU7yfUuIMAVRKql4f9uNiX5q5LafSL7mekdP2lB03GJFDgc78yVUKIdqIqWd8qav48nTQoskDxGeVNhi7m1HEPNdVBXardJV3Pegx2z5Rinl9OvdlJ+TxRYgLtHH6FZQqFtGZP2KEJAQ70yWCREXslojZUy9ujHdqK9gjAQZJcidF+172V9m/TpT3aPF335JD31saHAd9aKksv4nQHLCtYVd24PT4ZMHMjAJ9kIt5BX+VvxEdLGxd6nlhmRg6YuQ0WfpbD2rh30RM/Md2h63quuicqxqvm3YaU6qykboGccuXw1aUDm6YHR0zHW5PoRLrIjxuUyLKZ+whd6Wp+u4lSnWEFUyMEYe+0uBakkhpu9h9Tel31v13OpJG2L/qIcZGKMzuQjfLTc5hwiwRC75lM3S7G8rU5Rv9g/Y2lImuIV6heGKTqZ47lnGoVPWCQsiRxyeoL1WC7H1sJaxQfwQqwauiyw/FUxwTJnCmOIbjUp4vVb9y00fnT61dAMQYLhlwnR03E1LrnHvjx80cNQf3flrQiWSgvT0V2KM0KPDqtZTYied5pVz4znTEMS1B4opXUDyfax28MbkRlYb99zXTDyfjbOQ/mP6b4Il9eR4TluGGeUohMo7TXg84="
after_success:
  - bundle exec codeclimate-test-reporter
