sudo: false
language: ruby
rvm:
  - 2.4.1
env:
  - START_SIMPLECOV=1
addons:
  code_climate:
    repo_token:
      secure: "r/gVaNeW11W40SfWNRSIlUM5pnJDSKv3ddAqpHBmVpH03dvwi2KfN0M2UJex23vZF06ei4tAuZtYjfPHRHkX9jioTAeuUzxfOnmy0zNGNCKUhC6g4hYCnn6uXuUVOxTQw4AAwpAYVYvr5k7GCK1/nI9iffRsR44u1/AlNwlImkhr+UnVpCbPOgSeeLrCa+QNFaU7/dcN0eLpbiUHJ/56SbHDus9Ymsu5S7AWM9gvyWwgKfB5in7c4a38U3IYJpdVPyG+2CSqfnvRPUlx9Tp4sIIKI/CaJvTZ0wez96yfRXotfac11+kXcAkAwFcbpieuWlJshoiULFHQT2ZrpmlhERk1Gt/0/dm20pChdD9UVw3dH7eorpLHkCva6u1Hqk6Ja6Y+hVDYbkviTkw49obPUUT1wyZCNrNqoWBDRr7ymJjZonz2QincXmIZTFsvshY9Y7xnRBnsquyLfEcqGu3cU06GxUH7UsNwNbI5SFKPh/awECakTucS0iU7EByMCpzyCMXOGmxwHeBK3TuZgKMSr80kj/q5MrU6AAX6pl0hlupEAyKK1vvmLN2LV4Wyhz/8O3fE03sPgXzCQ1ssJYt3Dr6r0miybBPdTW3CRYhibyAQJTCTKEpxZQr4TDn6rmdmUuaMYwzJKvJwimvLgJwETbMGBU7KDQrqL2aIb1lp8fo="
after_success:
  - bundle exec codeclimate-test-reporter
